language: cpp

env:
  - CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++
  
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target RUN_TESTS
  - cmake --build . --target RUN_UNICODE_TESTS
  - cmake --build . --target RUN_WIN9X_TESTS

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686
  - git submodule update --init --recursive
