language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf automake bash bison bzip2 cmake flex gettext git g++ intltool libtool libltdl-dev openssl libssl-dev libxml-parser-perl make patch perl pkg-config scons sed unzip wget xz-utils yasm
  - git clone -b stable https://github.com/mxe/mxe.git
  - cd mxe
  - export MXE_ROOT=`pwd`
  - make gcc boost
  - export PATH=$MXE_ROOT/usr/bin:$PATH
  - ls -l $MXE_ROOT
  - cd ..
  - git submodule update --init --recursive

script:
  - cmake . -DCMAKE_TOOLCHAIN_FILE=$MXE_ROOT/usr/i686-pc-mingw32/share/cmake/mxe-conf.cmake
  - cmake --build .
  - cmake --build . --target RUN_TESTS
  - cmake --build . --target RUN_UNICODE_TESTS
  - cmake --build . --target RUN_WIN9X_TESTS
