#=============================================================================
# Copyright (C) 2013 Daniel Pfeifer <daniel@pfeifer-mail.de>
# Copyright (C) 2013 Alexander Lamaison <awl03@doc.ic.ac.uk>
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#=============================================================================

language: cpp

compiler:
  - gcc

env:
  global:
    - OPTIONS="-DCMAKE_TOOLCHAIN_FILE=../cmake/i686-w64-mingw32.cmake"
    - DEPENDS="binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686 wine"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends $DEPENDS libboost-dev

script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE $OPTIONS .. && cmake --build .. && cmake --build .. --target RUN_TESTS